<?php
include_once __DIR__ . '/config.php';

$videofeed = @json_decode(file_get_contents(VIDEO_FEED_FILE), false); // updated by update.php
if ( !$videofeed )
    die("Error loading video feed. Please run /update.php to generate the feed (videofeed.json).");

// generated by https://chromewebstore.google.com/detail/pockettube-youtube-subscr/kdmnjgijlmjgmimahnillepgcgeemffb
$channels = json_decode(file_get_contents(CHANNELS_FILE), true);
if ( !$channels )
    die("Error loading " . CHANNELS_FILE . " channel list.");
?>

<!doctype html>
<head>
    <title>MiniTube</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">
    <link rel="stylesheet" href="style.css">
    <script>
    function filter_category(cat = '') {
        document.querySelectorAll('.video-entry').forEach(e => {
            // Show all if no category, otherwise show only matching
            e.hidden = cat !== '' && !e.classList.contains('category-' + cat);
        });
    }
    </script>
</head>
<body>
    <h1><span style="filter: saturate(8) hue-rotate(-200deg); margin-left: 5px;">▶️</span> MiniTube </h1>
    <div class='category-selector'>

        <a href="./rssfeed.php" target="_blank">
            <button>
            <svg style="width:32px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><g transform="translate(-39 -82)"><rect width="100" height="100" x="40" y="82" fill="#ff6f22" ry="11"/><path fill="none" stroke="#fefefe" stroke-linecap="round" stroke-linejoin="round" stroke-width="17.1" d="M59 101a62 63 0 0 1 62 63"/><path fill="none" stroke="#fefefe" stroke-linecap="round" stroke-linejoin="round" stroke-width="11.6" d="M56 124a42 42 0 0 1 42 42"/><path fill="none" stroke="#fefefe" stroke-linecap="round" stroke-linejoin="round" stroke-width="6.8" d="M55 143a25 25 0 0 1 24 25"/></g></svg>
            </button>
        </a>
    <?php
    echo "<button onclick='filter_category()'>Show All</button> ";
    foreach (array_keys($channels) as $category) {
        if( !str_starts_with($category, "ysc_") )   // skip pockettubes' special categories
            echo "<button onclick=\"filter_category('$category')\">" . $category . "</button> ";
    }
    ?>
    </div>

    <div class='video-grid'>
    <?php foreach ($videofeed as $video): ?>
        <div class='video-entry category-<?= $video->category ?>'>
            <a href='https://www.youtube.com/watch?v=<?= $video->videoId ?>' target='_blank'>
                <img class='video-thumbnail' src='https://img.youtube.com/vi/<?= $video->videoId ?>/0.jpg' loading='lazy'>
                <div class='video-date'><?= (new DateTime($video->publishdate))->format('m-d H:i') ?></div>
                <div class='video-channel'><a href='https://youtube.com/channel/<?= $video->channelid ?>' target='_blank'><?= ucfirst(htmlspecialchars($video->channelname)) ?></a></div>
            </a>
            <div class='video-title'><?= htmlspecialchars($video->title) ?></div>
            <a href='./download.php?video=https://youtube.com/watch?v=<?= $video->videoId ?>' target='_blank'><button>⏬ Download</button></a>
        </div>
    <?php endforeach; ?>
    </div>
</body>
</html>